### ISSUE TITLE
Erro no nome do Domínio

### ISSUE THREAD

**Issue by dgomp** [riservato-xyz/whaticket-installer#10]
Olá,

Tentei criar no formato original (**https://localhost:3000** pra frontend e **http://localhost** pra backend), mas deu o seguinte erro:

_Error creating new order :: Cannot issue for "http": Domain name needs at least one dot (and 1 more problems. Refer to sub-problems for more information.)_

Tentei também alterando o frontend para **https://127.0.0.1:3000** e o backend para **http://127.0.0.1**, mas deu o seguinte erro:
_Error creating new order :: Cannot issue for "127.0.0.1": The ACME server can not issue a certificate for an IP address (and 1 more problems. Refer to sub-problems for more information.)_

Outro formato que tentei, foi **127.0.0.1:3000** para frontend e **127.0.0.1** para backend, e o erro foi o a seguir:
_Requested name 127.0.0.1 is an IP address. The Let's Encrypt certificate authority will not issue certificates for a bare IP address._

Como devo proceder?
Obrigado.

**Comment by dev-stupid-codes** [comment]
Este instalador não tem suporte à instalação com localhost ou IP.

Caso queira rodar whaticket sem domínio ou localmente, terá que instalar manualmente.
