### ISSUE TITLE
BUG: Configurando certbot...

### ISSUE THREAD

**Issue by tellmoitas** [riservato-xyz/whaticket-installer#4]
💻 Configurando certbot...

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [emerg] "user" directive is not allowed here in /etc/nginx/conf.d/whaticket.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed

The nginx plugin is not working; there may be problems with your existing configuration.
The error was: MisconfigurationError('Error while running nginx -c /etc/nginx/nginx.conf -t.\n\nnginx: [emerg] "user" directive is not allowed here in /etc/nginx/conf.d/whaticket.conf:1\nnginx: configuration file /etc/nginx/nginx.conf test failed\n')

**Comment by dev-stupid-codes** [comment]
Esse commit resolve o problema: https://github.com/riservato-xyz/whaticket-installer/commit/27cc98913b708b64134ed62829d2521c8492dbdb

Faça o seguinte:

```
sudo rm -rf /etc/nginx/conf.d/whaticket.conf
echo 'client_max_body_size 20M;' | sudo tee -a /etc/nginx/conf.d/whaticket.conf > /dev/null
service nginx restart
sudo certbot --nginx
```
Se não conseguir resolver usando estes comandos, você pode sempre recriar o VPS e usar o instalador novamente.

**Comment by dev-stupid-codes** [comment]
Se necessário, pode me passar os dados de acesso via SSH que eu resolvo.

dev@riservato.xyz
